program ::= queryStatement* EOF

queryStatement ::= selectStatement

selectStatement ::= "SELECT" ( identifiers | "*" ) fromClause whereClause?

identifiers ::= IDENTIFIER ( "," IDENTIFIER )*

fromClause ::= "FROM" expression ( "," expression )?

whereClause ::= "WHERE" expression

literal ::= 'nil' | 'false' | 'true' | NUMBER | STRING

expression ::= logicOr
logicOr = logicAnd ( "OR" logicAnd )*
logicAnd = equality ( "AND" equality )*
equality ::= comparison ( ( "!=" | "==" ) comparison )*
comparison ::= term ( ( ">" | ">=" | "<" | "<=" ) term )*
term ::= factor ( ( "-" | "+" ) factor )*
factor ::= unary ( ( "/" | "*" ) unary )*
unary ::= ( "!" | "-" ) unary | get
get ::= primary (( "." IDENTIFIER ) | "[" ( expression | STRING ) "]")*
primary ::= literal | "(" expression ")" | IDENTIFIER | $selected