program ::= queryStatement* EOF

queryStatement ::= selectStatement | updateStatement

selectStatement ::= "select" classSelector fromClause whereClause?

updateStatement ::= "update" classSelector setClause fromClause

classSelector ::= identifiers | "*"

setClause ::= "set" assignment ( "," assignment )*

assignment ::= IDENTIFIER "=" expression

identifiers ::= IDENTIFIER ( "," IDENTIFIER )*

fromClause ::= "from" expression ( "," expression )?

whereClause ::= "where" expression

literal ::= 'nil' | 'false' | 'true' | NUMBER | STRING

expression ::= logicOr
logicOr = logicAnd ( "OR" logicAnd )*
logicAnd = equality ( "AND" equality )*
equality ::= comparison ( ( "!=" | "==" ) comparison )*
comparison ::= term ( ( ">" | ">=" | "<" | "<=" ) term )*
term ::= factor ( ( "-" | "+" ) factor )*
factor ::= unary ( ( "/" | "*" ) unary )*
unary ::= ( "!" | "-" ) unary | get
get ::= primary (( "." IDENTIFIER ) | "[" ( expression | STRING ) "]")*
primary ::= NUMBER | STRING | "true" | "false" | "nil" | "(" expression ")" | IDENTIFIER